# Generated by Django 3.1.1 on 2020-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
